spring:
  application:
    name: reward-redemption

  datasource:
    url: jdbc:mysql://localhost:3306/reward_redemption
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: reward_activity
    local-datacenter: datacenter1
    schema-action: none

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    clean-disabled: false
