spring:
  application:
    name: reward-redemption

  datasource:
    url: jdbc:mysql://localhost:3306/reward_redemption
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  cassandra:
    contact-points: localhost
    port: 9042
    keyspace-name: reward_activity
    local-datacenter: datacenter1
    schema-action: none

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.rewardredemption.transaction.event

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    clean-disabled: false
